# Generated by Django 5.0.3 on 2024-03-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_product_cat_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=255, verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='extra_attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Додаткові атрибуты'),
        ),
    ]
