# Generated by Django 5.0.3 on 2024-04-10 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.IntegerField(blank=True, null=True, verbose_name='DPI')),
                ('key_type', models.CharField(blank=True, max_length=100, verbose_name='Тип клавиш')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='goods.product')),
            ],
        ),
    ]
