# Generated by Django 5.0.3 on 2024-04-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='key_type',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value',
            field=models.CharField(blank=True, max_length=100, verbose_name='value'),
        ),
    ]
