# Generated by Django 5.0.3 on 2024-04-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_productattribute_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Атрібут', 'verbose_name_plural': 'Атрібути'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_attributes',
        ),
    ]
