# Generated by Django 5.0.3 on 2024-05-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='value')),
            ],
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='value', to='goods.attributesvalues', verbose_name='Значення'),
        ),
    ]
