# Generated by Django 5.0.3 on 2024-05-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_attributesnames_remove_productattribute_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributesnames',
            options={'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибути'},
        ),
        migrations.AlterModelOptions(
            name='attributesvalues',
            options={'verbose_name': 'Значення атрибута', 'verbose_name_plural': 'Значення атрибутів'},
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.SmallIntegerField(default=0, verbose_name='Гарантія(міс)'),
        ),
    ]
