# Generated by Django 5.0.3 on 2024-05-25 18:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0021_wish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wish',
            unique_together={('user', 'product', 'session_key')},
        ),
    ]
